apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-kaniko-pipeline
spec:
  workspaces:
    - name: source
  params:
    - name: repository
    - name: image
  tasks:
    - name: git
      workspaces:
        - name: source
      params:
        - name: repository
          value: $(params.repository)
      taskRef:
        name: git
    - name: kaniko
      runAfter:
        - git
      workspaces:
        - name: source
      params:
        - name: image
          value: $(params.image)
      taskRef:
        name: kaniko
